### ISSUE TITLE
Consider making a new release

### ISSUE THREAD

**Issue by paolobarbolini** [caspervonb/serde_nanos#7]
While scanning through crates.io tarballs I've found your crate to be missing the `repository` field. This has been fixed in 705bd7642cb04c1ca932ff10bb64264e74aa783b, but hasn't been released yet.

Could you make a new crates.io release? Bumping just the patch version should be sufficient given the changes on `main`.

**Comment by caspervonb** [comment]
Will do.

**Comment by paolobarbolini** [comment]
Thank you
